name: medhub
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:  
  uses-material-design: true

  assets:
  - assets/images/
  - assets/icons/

  fonts:
    - family: Overpass
      fonts:
        - asset: assets/fonts/Overpass/Overpass-Bold.ttf
          weight: 700
        - asset: assets/fonts/Overpass/Overpass-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Overpass/Overpass-Medium.ttf
          weight: 500
        - asset: assets/fonts/Overpass/Overpass-Regular.ttf
          weight: 400
        - asset: assets/fonts/Overpass/Overpass-Light.ttf
          weight: 300
        - asset: assets/fonts/Overpass/Overpass-Thin.ttf
          weight: 200
  